# Generated by Django 5.2.7 on 2026-03-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_documentupload_status_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='classification_time',
            field=models.FloatField(blank=True, help_text='Time taken for classification in seconds', null=True),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='total_processing_time',
            field=models.FloatField(blank=True, help_text='Total processing time including extraction in seconds', null=True),
        ),
    ]
