# Generated by Django 5.2.7 on 2026-04-06 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_documentupload_classification_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('for_review', 'For Review'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                ],
                db_index=True,
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                choices=[('faculty', 'Faculty'), ('admin', 'Admin')],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['user', '-created_at'], name='docupload_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['user', 'status'], name='docupload_user_status_idx'),
        ),
    ]
