# Generated by Django 5.2.7 on 2026-04-10 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_indexes_and_cache_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='ClassificationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('predicted_primary_kra', models.CharField(max_length=255)),
                ('predicted_criteria', models.CharField(max_length=255)),
                ('predicted_sub_criteria', models.CharField(max_length=255)),
                ('corrected_primary_kra', models.CharField(max_length=255)),
                ('corrected_criteria', models.CharField(max_length=255)),
                ('corrected_sub_criteria', models.CharField(max_length=255)),
                ('was_correct', models.BooleanField(db_index=True, default=False)),
                ('feedback_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_feedback', to='api.documentupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_feedback_entries', to='api.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='classificationfeedback',
            index=models.Index(fields=['content_hash', '-created_at'], name='feedback_hash_created_idx'),
        ),
    ]
